# Generated by Django 4.2.3 on 2023-12-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetail',
            name='contact_info',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
