# Generated by Django 4.2.3 on 2023-12-23 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_companydetail_contact_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(blank=True, editable=False, max_length=256)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('company_logo', models.ImageField(blank=True, upload_to='images/company/logo/')),
                ('address', models.CharField(blank=True, max_length=126)),
                ('contact_info', models.TextField(blank=True, max_length=500, null=True)),
                ('terms_and_conditions', models.TextField(max_length=500, null=True)),
                ('company_vat', models.IntegerField(null=True)),
                ('pan_number', models.CharField(blank=True, help_text='Enter company PAN number', max_length=200)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CompanyDetail',
        ),
    ]
