# Generated by Django 4.2.3 on 2023-12-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_company_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(blank=True, max_length=125, unique=True),
        ),
    ]
