version: "3.8"

services:
  web:
    container_name: crms
    build:
      context: . # Points to the project root
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8080
    env_file:
      - ./.env
    depends_on:
      - db

  redis:
    image: redis
    container_name: crms-redis
    ports:
      -  "6380:6379"

  db:
    image: postgres:15
    container_name: website-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
volumes:
  postgres_data:
