version: "3.8"

services:
  web:
    container_name: aprs
    build:
      context: . # Points to the project root
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8001:8001
    env_file:
      - ./.env
    depends_on:
      - db

  redis:
    image: redis
    container_name: aprs-redis
    ports:
      -  "6381:6381"

  db:
    image: postgres:15
    container_name: aprs-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
volumes:
  postgres_data:
