# Generated by Django 4.2.3 on 2023-12-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='10 square foot room', max_length=1000),
            preserve_default=False,
        ),
    ]
