# Generated by Django 4.2.3 on 2023-12-23 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0005_userdetail_user_type'),
        ('property', '0004_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(help_text='One to borrows the property or place', on_delete=django.db.models.deletion.PROTECT, to='autho.userdetail'),
        ),
    ]
