# Generated by Django 4.2.3 on 2023-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_leaseinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='leaseinformation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Enter amount eg:1000', max_digits=10),
        ),
        migrations.AlterField(
            model_name='leaseinformation',
            name='tax',
            field=models.DecimalField(decimal_places=2, help_text='enter tax percentage', max_digits=5),
        ),
    ]
