# Generated by Django 4.2.3 on 2023-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_tenant_title_alter_leaseinformation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseinformation',
            name='lease_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active'),
        ),
    ]
