# Generated by Django 4.2.3 on 2023-12-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_leaseinformation_lease_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseinformation',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaseinformation',
            name='lease_status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('late', 'Late by')], default='active'),
        ),
    ]
