# Generated by Django 4.2.3 on 2023-12-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_leaseinformation_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseinformation',
            name='lease_status',
            field=models.CharField(choices=[('not_active', 'Not Active'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('late', 'Late by')], default='not_active'),
        ),
    ]
