# Generated by Django 4.2.3 on 2023-12-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0006_alter_userdetail_user_type'),
        ('property', '0010_alter_leaseinformation_lease_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.ForeignKey(help_text='One who borrows the property or place', on_delete=django.db.models.deletion.PROTECT, to='autho.userdetail'),
        ),
    ]
