# Generated by Django 4.2.3 on 2023-12-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_alter_tenant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaseinformation',
            name='due_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
