# Generated by Django 4.2.3 on 2023-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_leaseinformation_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='upload_document',
            field=models.FileField(blank=True, null=True, upload_to='image/tenant/documents/'),
        ),
        migrations.AlterField(
            model_name='leaseinformation',
            name='due_date',
            field=models.DateField(editable=False, null=True, verbose_name='billing date'),
        ),
    ]
