REGISTER_USER = "RegisteredUser"
SUPER_USER = "Superuser"
ADMIN_USER = "Admin"
ANONYMOUS_USER = "AnonymousUser"
REPORT_ROLE = "ReportAdmin"
SUPER_ADMIN = "SuperAdmin"

PRIMARY_ROLES = [
    SUPER_USER,
    REGISTER_USER,
    ADMIN_USER,
    ANONYMOUS_USER,
    REPORT_ROLE,
    SUPER_ADMIN,
]
