# Generated by Django 4.2.3 on 2024-01-20 04:09

import autho.manager.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('number', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=126, null=True)),
                ('dob', models.DateField(help_text='Enter date of birth', null=True)),
                ('user_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active')),
                ('user_type', models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('staff', 'Staff'), ('customer', 'Customer'), ('admin', 'Admin')], default='customer')),
                ('profile_pic', models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='')),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('objects', autho.manager.manager.BaseAuthManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=250)),
                ('login_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autho.userdetail')),
            ],
        ),
    ]
