# Generated by Django 4.2.3 on 2023-12-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0003_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active'),
        ),
    ]
