# Generated by Django 4.2.3 on 2023-12-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0004_userdetail_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('staff', 'Staff'), ('customer', 'Customer')], default='owner'),
        ),
    ]
