# Generated by Django 4.2.3 on 2023-12-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0005_userdetail_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='user_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('tenant', 'Tenant'), ('staff', 'Staff'), ('customer', 'Customer')], default='customer'),
        ),
    ]
