# Generated by Django 4.2.3 on 2023-12-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0006_alter_userdetail_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
