# Generated by Django 4.2.3 on 2023-12-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autho', '0007_userdetail_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to=''),
        ),
    ]
