# Generated by Django 4.2.3 on 2023-12-25 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autho', '0008_alter_userdetail_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iid', models.CharField(blank=True, editable=False, max_length=256)),
                ('created_at', models.DateTimeField(blank=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('staff_id', models.CharField(max_length=125, unique=True)),
                ('joined_date', models.DateField()),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('position', models.CharField(blank=True, max_length=256)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autho.userdetail')),
            ],
            options={
                'verbose_name': 'Staff',
            },
        ),
    ]
