from permissions.managepermission.users_permissions import (
    STAFF_API,
    DEPARTMENT_API,
    ATTENDANCE_API,
    COMPANY_API,
    ATTEN_REQUEST_API,
    ATTENDANCE_REQUEST_STATUS_API,
    ATTENDANCE_REQUEST_GET_STAFF_API,
    LEAVE_REQUEST_API,
    UPDATE_LEAVE_REQUEST,
)


GET_ALL_PERMISSION = [
    STAFF_API,
    DEPARTMENT_API,
    ATTENDANCE_API,
    COMPANY_API,
    ATTEN_REQUEST_API,
    ATTENDANCE_REQUEST_STATUS_API,
    ATTENDANCE_REQUEST_GET_STAFF_API,
    LEAVE_REQUEST_API,
    UPDATE_LEAVE_REQUEST,
]
